### ISSUE TITLE
Create currency input

### ISSUE THREAD

**Issue by arathjz** [codelittinc/agnostic-design-system#247]
We use a currency input in the appraisal app; however, there's no currency input available in the ADS components library. I propose to create something similar as the following example:

https://codesandbox.io/s/react-currency-input-with-react-text-mask-4es23?from-embed=&file=/src/CurrencyInput.js

**Comment by kaiomagalhaes** [comment]
@arathjz is there anything that we would offer here that isn't available in the Numeric Input?

**Comment by arathjz** [comment]
Hey @kaiomagalhaes, I haven't used the input recently. I will take a look and see if this was already addressed
